const products = [
  {
    name: 'Deceit Black Tshirt',
    image: '/img/deceit_black_tshirt.jpeg',
    description: 'Black Tshirt with the Deceit artwork',
    category: 'Tshirt/Clothing',
    price: 15.0,
    countInStock: [
      { size: 'small', stock: 5 },
      { size: 'medium', stock: 8 },
      { size: 'large', stock: 6 },
      { size: 'xl', stock: 7 },
      { size: 'xxl', stock: 2 },
    ],
  },
  {
    name: 'Deceit Burgundy Tshirt',
    image: '/img/deceit_burgundy_tshirt.jpeg',
    description: 'Burgundy Tshirt with the Deceit artwork',
    category: 'Tshirt/Clothing',
    price: 15.0,
    countInStock: [
      { size: 'small', stock: 5 },
      { size: 'medium', stock: 8 },
      { size: 'large', stock: 6 },
      { size: 'xl', stock: 7 },
      { size: 'xxl', stock: 2 },
    ],
  },
  {
    name: 'Deceit pink Tshirt',
    image: '/img/deceit_pink_tshirt.jpeg',
    description: 'Black Tshirt with the Deceit artwork',
    category: 'Tshirt/Clothing',
    price: 15.0,
    countInStock: [
      { size: 'small', stock: 5 },
      { size: 'medium', stock: 8 },
      { size: 'large', stock: 6 },
      { size: 'xl', stock: 7 },
      { size: 'xxl', stock: 2 },
    ],
  },
  {
    name: 'Where Truth Occurs White Tshirt',
    image: '/img/truth_white_tshirt.jpeg',
    description: 'Where truth occurs Tshirt with album artwork',
    category: 'Tshirt/Clothing',
    price: 15.0,
    countInStock: [
      { size: 'small', stock: 5 },
      { size: 'medium', stock: 8 },
      { size: 'large', stock: 6 },
      { size: 'xl', stock: 7 },
      { size: 'xxl', stock: 2 },
    ],
  },
  {
    name: 'Scathed Charcoal Hat',
    image: '/img/scathed_charcoal_hat.jpeg',
    description: 'Scathed charcoal beanie',
    category: 'Beanie/Clothing',
    price: 10.0,
    countInStock: [{ size: 'single', stock: 2 }],
  },
  {
    name: 'Scathed Cream Hat',
    image: '/img/scathed_cream_hat.jpeg',
    description: 'Scathed cream beanie',
    category: 'Beanie/Clothing',
    price: 10.0,
    countInStock: [{ size: 'single', stock: 6 }],
  },
  {
    name: 'Scathed Pink Hat',
    image: '/img/scathed_pink_hat.jpeg',
    description: 'Scathed pink beanie',
    category: 'Beanie/Clothing',
    price: 10.0,
    countInStock: [{ size: 'single', stock: 9 }],
  },
  {
    name: 'Scathed Rust Hat',
    image: '/img/scathed_rust_hat.jpeg',
    description: 'Scathed rust beanie',
    category: 'Beanie/Clothing',
    price: 10.0,
    countInStock: [{ size: 'single', stock: 5 }],
  },
  {
    name: 'Where truth occurs EP',
    image: '/img/scathed_where_truth_occurs.jpeg',
    description:
      '4 panel Digi pack with artwork and layout by Kelvin Doran of Serpent Tusk Studio',
    category: 'Music/CD',
    price: 5.0,
    countInStock: [{ size: 'single', stock: 8 }],
  },
];

module.exports = products;
